#!/bin/bash 
 

# sbatch ./batchcluster_init_findtrees_1.sh
sbatch ./batchcluster_init_findtrees_2.sh
sbatch ./batchcluster_init_findtrees_3.sh
sbatch ./batchcluster_init_findtrees_4.sh
sbatch ./batchcluster_init_findtrees_5.sh
sbatch ./batchcluster_init_findtrees_6.sh
sbatch ./batchcluster_init_findtrees_7.sh
sbatch ./batchcluster_init_findtrees_8.sh
sbatch ./batchcluster_init_findtrees_9.sh
sbatch ./batchcluster_init_findtrees_10.sh
sbatch ./batchcluster_init_findtrees_11.sh
sbatch ./batchcluster_init_findtrees_12.sh
sbatch ./batchcluster_init_findtrees_13.sh
sbatch ./batchcluster_init_findtrees_14.sh
sbatch ./batchcluster_init_findtrees_15.sh
sbatch ./batchcluster_init_findtrees_16.sh
sbatch ./batchcluster_init_findtrees_17.sh
sbatch ./batchcluster_init_findtrees_18.sh
sbatch ./batchcluster_init_findtrees_19.sh
sbatch ./batchcluster_init_findtrees_20.sh
sbatch ./batchcluster_init_findtrees_21.sh
sbatch ./batchcluster_init_findtrees_22.sh
sbatch ./batchcluster_init_findtrees_23.sh
sbatch ./batchcluster_init_findtrees_24.sh
# sbatch ./batchcluster_init_findtrees_25.sh
sbatch ./batchcluster_init_findtrees_26.sh
sbatch ./batchcluster_init_findtrees_27.sh
sbatch ./batchcluster_init_findtrees_28.sh
sbatch ./batchcluster_init_findtrees_29.sh
sbatch ./batchcluster_init_findtrees_30.sh
sbatch ./batchcluster_init_findtrees_31.sh
sbatch ./batchcluster_init_findtrees_32.sh
sbatch ./batchcluster_init_findtrees_33.sh
sbatch ./batchcluster_init_findtrees_34.sh
sbatch ./batchcluster_init_findtrees_35.sh
sbatch ./batchcluster_init_findtrees_36.sh
sbatch ./batchcluster_init_findtrees_37.sh
sbatch ./batchcluster_init_findtrees_38.sh
sbatch ./batchcluster_init_findtrees_39.sh
sbatch ./batchcluster_init_findtrees_40.sh
sbatch ./batchcluster_init_findtrees_41.sh
sbatch ./batchcluster_init_findtrees_42.sh
sbatch ./batchcluster_init_findtrees_43.sh
sbatch ./batchcluster_init_findtrees_44.sh
sbatch ./batchcluster_init_findtrees_45.sh
sbatch ./batchcluster_init_findtrees_46.sh
sbatch ./batchcluster_init_findtrees_47.sh
sbatch ./batchcluster_init_findtrees_48.sh
sbatch ./batchcluster_init_findtrees_49.sh
sbatch ./batchcluster_init_findtrees_50.sh
sbatch ./batchcluster_init_findtrees_51.sh
sbatch ./batchcluster_init_findtrees_52.sh
sbatch ./batchcluster_init_findtrees_53.sh
sbatch ./batchcluster_init_findtrees_54.sh
sbatch ./batchcluster_init_findtrees_55.sh
sbatch ./batchcluster_init_findtrees_56.sh
sbatch ./batchcluster_init_findtrees_57.sh
sbatch ./batchcluster_init_findtrees_58.sh
sbatch ./batchcluster_init_findtrees_59.sh
sbatch ./batchcluster_init_findtrees_60.sh
sbatch ./batchcluster_init_findtrees_61.sh
sbatch ./batchcluster_init_findtrees_62.sh
sbatch ./batchcluster_init_findtrees_63.sh
sbatch ./batchcluster_init_findtrees_64.sh
sbatch ./batchcluster_init_findtrees_65.sh
