# er-forest-inventory_config.yml

default:
 key1: default
 driveauth: 'config/eastriver-r-googledrive-clientsecret.json'
 drivekey: 'config/eastriver-r-googledrive_auth.txt'
 email: 'worsham@berkeley.edu'
 pkgs:
  - tidyverse
  - googledrive
  - readxl
  - sf
  - terra
  - xfun
 extdata:
   invpattern: 'inventory_data'
   stemid: '1qkZSAQsqbfPX_r8tkorAQs5dRbCcIXPg'
   stempattern: 'Stem_Geolocations_WGS84UTM13N'
   rawgpsid: '1MC4ucuVidD7BpvXe_EImcjLDVDgEPFq8'
   gpsidx: 'EastRiver_GPS_Data_Index'
 dat_raw: './data/raw'
 dat_int: './data/intermediate'
 dat_pro: './data/processed'
 dat_merged: './data/intermediate/GPS_Data_Merged_2021'
 dat_stemgeo: './data/processed/Kueppers_EastRiver_Stem_Geolocations_WGS84UTM13N'

test:
  key1: test

production:
  key1: production
