# er-forest-inventory_config.yml

default:
 key1: default
 pkgs:
  - tidyverse
  - googledrive
  - readxl
  - sf
  - terra
  - xfun
 extdata:
   invpattern: 'inventory_data'
   stemid: '1qkZSAQsqbfPX_r8tkorAQs5dRbCcIXPg'
   stempattern: 'Stem_Geolocations_WGS84UTM13N'
   rawgpsid: '1MC4ucuVidD7BpvXe_EImcjLDVDgEPFq8'
 dat_raw: './data/raw'
 dat_int: './data/intermediate'
 dat_pro: './data/processed'

test:
  key1: test

production:
  key1: production
