# er-forest-structure_config.yml

default:
 key1: default
 driveauth: '~/.ssh/eastriver-r-googledrive-clientsecret.json'
 drivesa: '~/.ssh/eastriver-308601-65de0446573f.json'
 mapkey: '~/.ssh/eastriver-r-googlemaps-key.txt'
 pkgs:
  - devtools
  - xfun
  - tidyverse
  - ggplot2
  - ggpattern
  - ggmap
  - usmap
  - ggspatial
  - gridExtra
  - patchwork
  - grid
  - gtable
  - tagger
  - terra
  - sf
  - future
  - parallel
  - doParallel
  - lidR
  - lidRplugins
  - rlas
  - ForestTools
  - FedData
  - rgl
  - nngeo
  - broom
  - plot3D
  - readxl
  - googledrive
  - rwaveform
  - optmatch
  - lattice
  - mgcv
  - corrplot
  - visreg
  - psych
  - raster
  - tidyterra
  - RColorBrewer
  - viridis
  - lme4
  - gbm
  - caret
  - car
  - officedown
  - jtools
  - flextable
  - ftExtra

 extdata:
  scratch: '/global/scratch/users/worsham'
  las_dec: '/global/scratch/users/worsham/las_decimated'
  las_reg: '/global/scratch/users/worsham/las_regridded'
  trees: '/global/scratch/users/worsham/trees_ls_100m_csv'
  itc: '/global/scratch/users/worsham/itc_results'
  siteindex: '1KPpaiTZSfrq0RYMJQwNdwgCU-4rWucheW5KUN_maERs'
  invpattern: 'EastRiver_Census1_Data_Collated.csv'
  invid: '17V27lVbOqh3dIhHQ24tiJpmpJeurSGy9'
  plotid: '1xrIjs8noEwkfQnSy_VGMdNLmfEr9RUEC'
  plotpattern: 'Kueppers_EastRiver_AllPlots_poly_2021_WGS84UTM13N'
  lcpattern: 'UER_landcover_1m_v4.tif'
  bndid: '1nkfaomyxsOjsRgPH8W9Q5a9cDR7xg9Xr'
  bndpattern: 'SDP_Boundary'
  falcoid: '17hMfbqWv0bX6wNJD2fm2ci6GtCEvrat7'
  classid: '14BRJ_Jydcm_nWV0M4M1tWwgtC0g-XkWH'
  naipid: '1OT-7ORM9VHiAyZ9VyDsG3s-KROfQQjjO'
  devid: '16R1302uBv4zHcYMjJn3tv9z-q7yZZYN2'
  devpattern: 'EastRiver_Development'
  roadsid: '16StDFH3RO-e_JCqHVpvO6GUuWQKR0FwT'
  roadspattern: 'EastRiver_Roads_Buffered'
 data:
  raw: './data/raw'
  int: './data/intermediate'
  pro: './data/processed'
